sudo: required

# @TODO
# this should be `language: - haskell`
# https://github.com/travis-ci/travis-ci/issues/5711
language: sh

dist: trusty
group: edge

services:
  - docker

cache:
  directories:
    - $HOME/.stack/
    - client/node_modules/
    - client/bower_modules/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - sudo apt-get -qq update
  - sudo apt-get install -y node npm libpq5 libgmp10

install:
  - make setup
  - make

